import { createContext, useContext, useState, useEffect, type ReactNode } from "react";

export type Lang = "en" | "ar";

export const translations = {
  en: {
    dir: "ltr" as const,
    appName: "Clearhead",
    tagline: "Expert psychiatric care, wherever you are",
    subTagline: "Connect with board-certified psychiatrists and therapists who truly listen. Evidence-based treatment for anxiety, depression, ADHD, PTSD, and more — from the comfort of home.",
    nav: {
      home: "Home", providers: "Providers", specialties: "Specialties",
      mySessions: "My Sessions", platform: "Platform", getStarted: "Get Started",
      pricing: "Pricing", simulator: "Revenue Simulator", legal: "Legal & Contracts",
      addDoctor: "Add a Doctor",
    },
    providers: {
      title: "Find a Provider",
      subtitle: "Board-certified specialists matched to your needs, priced in your local currency.",
      search: "Search by name...",
      allSpecialties: "All Specialties",
      anyGender: "Any gender",
      maleProviders: "Male providers",
      femaleProviders: "Female providers",
      availableNow: "Available now",
      found: "providers found",
      pricesIn: "Prices shown in",
      bookSession: "Book a Session",
      available: "Available",
      waitlisted: "Waitlisted",
      insurance: "Insurance",
      exp: "y exp.",
      next: "Next:",
      reviews: "reviews",
    },
    intake: {
      stepOf: "Step",
      of: "of",
      yourJourney: "Your journey starts here",
      whatSupport: "What kind of support are you looking for?",
      chooseRight: "Choose what feels right — you can always adjust later.",
      whatBrings: "What brings you here?",
      chooseAll: "Choose all that apply — we'll tailor your match.",
      anySymptoms: "Any of these feel familiar?",
      preselected: "We've pre-selected based on what you shared. Remove or add as needed.",
      previousTherapy: "Have you been in therapy before?",
      age: "How old are you?",
      ageSubtitle: "Helps us match you with a provider experienced with your age group.",
      yearsOld: "years old",
      gender: "How do you identify?",
      country: "Where are you based?",
      countrySubtitle: "We'll match providers in your region and show prices in your local currency.",
      therapistGender: "Any preference for your therapist's gender?",
      religious: "Do you consider yourself religious or spiritual?",
      sessionFormat: "How would you like to meet?",
      contactMethod: "How should we reach you?",
      whatsappNumber: "Your WhatsApp number",
      phoneNumber: "Your phone number",
      emailAddress: "Your email address",
      howHeard: "One last thing — how did you find us?",
      termsTitle: "Almost there — review and accept",
      termsSubtitle: "Please read and accept the following before we match you with a provider.",
      iAgree: "I have read and accept all terms",
      continueBtn: "Continue",
      findTherapist: "Find my therapist",
      selectCountry: "Select your country...",
      suggested: "suggested",
      noPreference: "No preference",
      maleTherapis: "Male therapist",
      femaleTherapis: "Female therapist",
      condition: "What are you dealing with?",
      conditionSubtitle: "Select your primary concern. You can pick more than one.",
      otherCondition: "Describe your concern",
      otherPlaceholder: "Tell us more about what you're going through...",
      sessionDuration: "How long would you like your sessions?",
      durationSubtitle: "Longer sessions give more depth. You can change this anytime.",
    },
    checkout: {
      title: "Book your Session",
      subtitle: "Choose a slot and confirm your appointment.",
      provider: "Provider",
      specialty: "Specialty",
      duration: "Session duration",
      selectDate: "Select a date",
      selectTime: "Select a time slot",
      promoCode: "Promo / referral code",
      promoPlaceholder: "CLEAR20",
      apply: "Apply",
      orderSummary: "Order summary",
      session: "Session fee",
      discount: "Discount",
      total: "Total",
      confirmBook: "Confirm & Book Session",
      acceptTerms: "I accept the Terms of Service and Privacy Policy",
      successTitle: "Booking submitted for approval",
      successSub: "Your booking is pending admin approval. You'll receive a confirmation once it's approved.",
      invalidCode: "Invalid code",
      codeApplied: "applied!",
      min: "min",
      paymentMethod: "Payment method",
      payCredit: "Credit / Debit Card",
      payZain: "Zain Cash",
      payOrange: "Orange Money",
      payClickPay: "ClickPay (Jordan)",
      cardNumber: "Card number",
      cardExpiry: "Expiry (MM/YY)",
      cardCvv: "CVV",
      cardName: "Name on card",
      walletNumber: "Wallet phone number",
      pendingApproval: "Awaiting admin approval",
      patientId: "Patient ID",
      callPlatform: "Video call platform",
      doxyNote: "Your provider will send a Doxy.me room link before your session. No download required.",
      noCancelNote: "Bookings are non-cancellable once confirmed. Please choose your slot carefully.",
      backBtn: "Back",
    },
    addDoctor: {
      title: "Join as a Provider",
      subtitle: "Apply to list your practice on Clearhead. Our team reviews all applications within 48 hours.",
      fullName: "Full name",
      title2: "Professional title",
      specialty: "Primary specialty",
      bio: "Professional biography",
      bioPlaceholder: "Your training, experience, and therapeutic approach...",
      languages: "Languages spoken",
      nationality: "Nationality / Country",
      price: "Session price (USD, 45 min)",
      experience: "Years of experience",
      credentials: "Credentials / Certifications",
      imageUrl: "Profile photo URL",
      email: "Contact email",
      phone: "Phone number",
      acceptsInsurance: "Accepts insurance",
      submit: "Submit application",
      success: "Application submitted! We'll be in touch within 48 hours.",
    },
    terms: {
      notMedical: "Clearhead is NOT a medical service",
      notMedicalText: "The services provided through this platform are cognitive, psychological, and therapeutic in nature. They do not constitute medical diagnosis, treatment, or prescription of any kind. For medical emergencies, contact your local emergency services immediately.",
      consent: "Informed consent",
      consentText: "By proceeding, you confirm that you are voluntarily seeking mental health support and understand that sessions are for therapeutic and wellness purposes only.",
      confidentiality: "Confidentiality",
      confidentialityText: "All sessions are private and confidential. Information may only be disclosed if there is an imminent risk of harm to yourself or others, as required by applicable law.",
      communication: "Communication monitoring",
      communicationText: "Sessions may be recorded for quality assurance and clinical supervision purposes. You will be notified before any recording begins.",
      age: "Age requirement",
      ageText: "You confirm you are 18 years of age or older, or have parental / guardian consent to access these services.",
      jurisdiction: "Jurisdiction",
      jurisdictionText: "These terms are governed by the laws of the jurisdiction in which your selected provider is licensed to practice.",
    },
    journey: {
      phases: ["Screening", "Your Profile", "Preferences", "Book"],
      careTypePhase: "Phase 1 · Screening",
      careTypeTitle: "Who is this for?",
      careTypeSubtitle: "Your answer tailors the screening and provider match that follows.",
      careTypeStart: "Start screening",
      careTypes: [
        { id: "individual", label: "For myself",          sub: "Adult individual therapy or psychiatric consultation" },
        { id: "couples",    label: "For us as a couple",  sub: "Relationship counselling, communication, trust" },
        { id: "children",   label: "For my child or teen",sub: "Specialist support for under 18s" },
      ],
      k10IntroTitle: "Psychological distress check",
      k10IntroText: "The next 10 questions are from the Kessler Psychological Distress Scale (K10) — a clinically validated tool used worldwide. Think about how you've felt over the past 4 weeks.",
      k10Privacy: "Your responses are private and reviewed only by your chosen provider.",
      k10Badge: "K10 · Distress",
      k10Scale: [
        { val: 1, label: "None of\nthe time" },
        { val: 2, label: "A little\nof the time" },
        { val: 3, label: "Some of\nthe time" },
        { val: 4, label: "Most of\nthe time" },
        { val: 5, label: "All of\nthe time" },
      ],
      k10Qs: [
        "About how often did you feel tired out for no good reason?",
        "About how often did you feel nervous?",
        "About how often did you feel so nervous that nothing could calm you down?",
        "About how often did you feel hopeless about the future?",
        "About how often did you feel restless or fidgety?",
        "About how often did you feel so restless you could not sit still?",
        "About how often did you feel depressed or down?",
        "About how often did you feel that everything was an effort?",
        "About how often did you feel so sad that nothing could cheer you up?",
        "About how often did you feel worthless?",
      ],
      phq9IntroTitle: "Depression screening",
      phq9IntroText: "The next 9 questions come from the Patient Health Questionnaire (PHQ-9). Think about how often you've experienced each over the past 2 weeks.",
      phq9Disclaimer: "This is a screening tool only. Results are shared with your provider, not used to diagnose.",
      phq9Badge: "PHQ-9 · Depression",
      phq9Header: "Over the last 2 weeks, how often have you been bothered by…",
      phq9CrisisNote: "If you are in crisis, please call your local emergency line or a mental health helpline immediately.",
      phqScale: [
        { val: 0, label: "Not\nat all" },
        { val: 1, label: "Several\ndays" },
        { val: 2, label: "More than\nhalf the days" },
        { val: 3, label: "Nearly\nevery day" },
      ],
      phq9Qs: [
        "Little interest or pleasure in doing things",
        "Feeling down, depressed, or hopeless",
        "Trouble falling or staying asleep, or sleeping too much",
        "Feeling tired or having little energy",
        "Poor appetite or overeating",
        "Feeling bad about yourself — or that you are a failure or have let yourself or your family down",
        "Trouble concentrating on things, like reading or watching TV",
        "Moving or speaking so slowly that other people could notice — or being so fidgety that you moved around more than usual",
        "Thoughts that you would be better off dead, or thoughts of hurting yourself in some way",
      ],
      gad7IntroTitle: "Anxiety screening",
      gad7IntroText: "Almost done with Phase 1. These 7 questions use the Generalized Anxiety Disorder scale (GAD-7). Again, think about the past 2 weeks.",
      gad7Badge: "GAD-7 · Anxiety",
      gad7Qs: [
        "Feeling nervous, anxious, or on edge",
        "Not being able to stop or control worrying",
        "Worrying too much about different things",
        "Trouble relaxing",
        "Being so restless that it is hard to sit still",
        "Becoming easily annoyed or irritable",
        "Feeling afraid as if something awful might happen",
      ],
      resultsPhase: "Screening complete",
      resultsTitle: "Your results",
      resultsSubtitle: "These are screening scores — not a diagnosis. A licensed provider will review them with you.",
      riskTitle: "One of your responses needs attention",
      riskText: "You indicated thoughts of self-harm. A clinician will review your case and reach out within 24 hours. If you are in immediate danger, please call emergency services.",
      scoreLabels: ["Depression (PHQ-9)"],
      scoreLevels: ["Minimal", "Mild", "Moderate", "Moderately Severe"],
      recommendedLabel: "Recommended",
      screeningDisclaimer: "This report is a PHQ-9 depression screening summary only — not a medical diagnosis.",
      recommendations: {
        couples:             { label: "Couples Therapist",             reason: "Specialists in relationship dynamics, communication and conflict resolution." },
        children:            { label: "Child & Adolescent Specialist",  reason: "Trained to work with younger minds in a safe, age-appropriate environment." },
        psychiatrist:        { label: "Psychiatrist",                   reason: "Your results indicate symptoms that benefit most from medical evaluation and comprehensive psychiatric care." },
        therapistDepression: { label: "Therapist — Depression Focus",   reason: "Your PHQ-9 score suggests a structured therapy approach like CBT would be most beneficial." },
        counselor:           { label: "Therapist / Counsellor",         reason: "Your results suggest mild to moderate stress. A supportive therapist will help you build resilience and coping skills." },
      },
      continueToProfile: "Continue to profile",
      profilePhase: "Phase 2 · Your Profile",
      profileTitle: "Tell us about yourself",
      profileSubtitle: "This helps your provider understand your background and provide better care.",
      firstNameLabel: "First name",  firstNamePH: "Jane",
      lastNameLabel: "Last name",    lastNamePH: "Smith",
      dobLabel: "Date of birth",
      genderLabel: "Gender",
      nationalityLabel: "Nationality / Country of residence",
      maritalLabel: "Marital status",
      occupationLabel: "Occupation", occupationPH: "e.g. Teacher, Engineer, Student…",
      educationLabel: "Education level",
      genderOpts: [
        { value: "male",       label: "Male" },
        { value: "female",     label: "Female" },
        { value: "nonbinary",  label: "Non-binary" },
        { value: "prefer_not", label: "Prefer not to say" },
      ],
      maritalOpts: [
        { value: "single",    label: "Single" },
        { value: "married",   label: "Married" },
        { value: "partnered", label: "In a relationship" },
        { value: "divorced",  label: "Divorced / Separated" },
        { value: "widowed",   label: "Widowed" },
      ],
      educationOpts: [
        { value: "high_school", label: "High school" },
        { value: "bachelors",   label: "Bachelor's degree" },
        { value: "masters",     label: "Master's degree" },
        { value: "phd",         label: "PhD / Doctorate" },
        { value: "vocational",  label: "Vocational / Trade" },
        { value: "other",       label: "Other" },
      ],
      medTitle: "Medical & mental health background",
      medSubtitle: "All information is confidential and shared only with your provider.",
      prevTherapyLabel: "Have you been in therapy or counselling before?",
      prevDxLabel: "Any previous diagnoses? (select all that apply)",
      familyDxLabel: "Family history of mental health conditions?",
      medsLabel: "Are you currently taking any medications?",
      therapyOpts: [
        { value: "yes_helpful",     label: "Yes — it was helpful" },
        { value: "yes_not_helpful", label: "Yes — but it wasn't helpful" },
        { value: "no",              label: "No, this is my first time" },
        { value: "unsure",          label: "Not sure" },
      ],
      medicationOpts: [
        { value: "no",        label: "No" },
        { value: "yes_psych", label: "Yes — psychiatric medications" },
        { value: "yes_other", label: "Yes — other medications" },
        { value: "unsure",    label: "Unsure" },
      ],
      prevDxOptions: ["Depression","Anxiety disorder","Bipolar disorder","ADHD","PTSD","OCD","Eating disorder","Personality disorder","Schizophrenia","None of the above"],
      familyDxOptions: ["Depression","Anxiety","Bipolar","Schizophrenia","Addiction","None that I know of"],
      emergencyTitle: "Emergency contact",
      emergencySubtitle: "Someone we can reach in case of a clinical emergency. This is optional but recommended.",
      emergencyNameLabel: "Contact name",    emergencyNamePH: "Full name",
      emergencyRelLabel: "Relationship",     emergencyRelPH: "e.g. Partner, Parent, Friend",
      emergencyPhoneLabel: "Phone number",   emergencyPhonePH: "+1 555 000 0000",
      emergencyNote: "This information is only used in genuine clinical emergencies.",
      prefsPhase: "Phase 3 · Preferences",
      prefsTitle: "How would you like to connect?",
      prefsSubtitle: "Set your session preferences — you can always change these later.",
      formatLabel: "Session format",
      formatOpts: [
        { value: "video",     label: "Video call",  icon: "📹" },
        { value: "phone",     label: "Phone call",  icon: "📞" },
        { value: "messaging", label: "Messaging",   icon: "💬" },
      ],
      providerGenderLabel: "Provider gender preference",
      providerGenderOpts: [
        { value: "any",    label: "No preference" },
        { value: "male",   label: "Male provider" },
        { value: "female", label: "Female provider" },
      ],
      timePrefLabel: "Preferred session time",
      timeOpts: [
        { value: "any",       label: "Flexible" },
        { value: "morning",   label: "Mornings (before noon)" },
        { value: "afternoon", label: "Afternoons" },
        { value: "evening",   label: "Evenings (after 5pm)" },
      ],
      contactLabel: "How should we contact you?",
      contactOpts: [
        { value: "email",    label: "Email",    icon: "✉️" },
        { value: "whatsapp", label: "WhatsApp", icon: "💬" },
      ],
      emailInputLabel: "Email address",    emailPH: "you@example.com",
      whatsappInputLabel: "WhatsApp number", whatsappPH: "+1 555 000 0000",
      findProvider: "Find my provider",
      bookingPhase: "Phase 4 · Book your session",
      bookingTitle: "Your matched providers",
      bookingSubtitleBase: "Based on your screening, we recommend a",
      bookingSubtitleCurrency: "Prices shown in",
      recommendedSection: "Recommended for you",
      otherSection: "Other providers",
      noProviders: "No providers found. Try clearing your search.",
      searchPH: "Search by name or specialty…",
      durationTitle: "Session duration",
      durationSubtitleBase: "Prices shown in",
      durationSubtitleNationality: "based on your nationality.",
      minuteLabel: "minutes",
      bestValue: "Best value",
      dateTitle: "Choose a date",
      dateSubtitle: "Sessions available within the next 60 days.",
      timePickTitle: "Pick a time",
      timePickSubtitleBase: "Available slots for",
      timePickDateFirst: "Select a date first.",
      checkingSlots: "Checking availability…",
      bookedSlotsNote: "slot already booked",
      bookedSlotsPluralNote: "slots already booked",
      reviewTitle: "Review & confirm",
      reviewSubtitle: "Everything look right? Lock in your session.",
      patientLabel: "Patient",
      reviewDateLabel: "Date",
      reviewTimeLabel: "Time",
      reviewFormatLabel: "Format",
      reviewCountryLabel: "Country",
      promoLabel: "Promo code",
      promoOptional: "optional",
      promoPH: "e.g. CLEAR20",
      applyBtn: "Apply",
      sessionFee: "Session fee",
      discountLabel: "Discount",
      totalLabel: "Total",
      invalidPromo: "Invalid promo code",
      termsText: "I accept the Terms of Service & Privacy Policy. I understand Clearhead is a screening and therapy platform, not an emergency service.",
      confirmBtn: "Confirm & Book Session →",
      securityNote: "HIPAA-compliant · End-to-end encrypted · Free cancellation up to 24h",
      successTitle: "You're all set!",
      successSub: "Session confirmed with",
      successDateLabel: "Date",
      successTimeLabel: "Time",
      successDurationLabel: "Duration",
      successTotalLabel: "Total",
      shareBtn: "Share via WhatsApp",
      copyBtn: "Copy Booking Link",
      copiedBtn: "Copied!",
      homeBtn: "Back to Home",
      backBtn: "Back",
      homeNavBtn: "Home",
      tapToAnswer: "Tap an answer to continue",
      continueBtn: "Continue",
      continueToPrefs: "Continue to preferences",
      reviewBookingBtn: "Review booking",
      confirmBookBtn: "Confirm & Book Session",
      browseProviders: "Browse providers",
      selectedSuffix: "selected",
      minLabel: "/hr",
      insuranceLabel: "Insurance",
      expLabel: "y exp",
    },
    landing: {
      heroAvailable: "Providers available now",
      heroChoose: "Choose the type of care you're looking for",
      heroServices: [
        { id: "individual", emoji: "🧠", title: "Individual Therapy",   sub: "Adults 18 and above" },
        { id: "couples",    emoji: "💑", title: "Couples Counseling",   sub: "For you or with a partner" },
        { id: "children",  emoji: "🧒", title: "Children & Teens",     sub: "Under 18 years" },
      ],
      heroGetStarted: "Get started",
      heroBrowse: "Browse all providers instead",
      statsLabels: ["Providers", "Patients Served", "Satisfaction Rate", "Countries"],
      specialitiesTitle: "Conditions we treat",
      specialitiesSub: "Specialized care across the full spectrum of mental health needs.",
      specialistsCount: "specialists",
      viewAllSpecialties: "View all specialties",
      meetTitle: "Meet our specialists",
      meetSub: "All providers are board-certified and background-verified before joining Clearhead.",
      browseAll: "Browse all",
      viewProfile: "View profile",
      howTitle: "How Clearhead works",
      howSub: "Getting started takes less than 5 minutes.",
      howSteps: [
        { num: "01", title: "Tell us what you need",   desc: "Complete a brief intake to help us understand your goals and preferences." },
        { num: "02", title: "Match with a specialist", desc: "Browse board-certified psychiatrists who specialize in your area of focus." },
        { num: "03", title: "Book your session",       desc: "Choose a time that fits your schedule — video, phone, or messaging." },
        { num: "04", title: "Start feeling better",    desc: "Get evidence-based care from the comfort of your home, on your terms." },
      ],
      getStartedToday: "Get started today",
      trustItems: [
        { label: "HIPAA Compliant",      desc: "All sessions are fully encrypted and private." },
        { label: "Board-Certified Only", desc: "Every provider is rigorously credentialed." },
        { label: "47 Countries Served",  desc: "Access care anywhere in the world." },
        { label: "Flexible Scheduling",  desc: "Evening and weekend appointments available." },
      ],
      testimonialsTitle: "What patients are saying",
      testimonialsSub: "Real stories from people who found their way forward.",
      ctaTitle: "You deserve to feel better.",
      ctaSub: "Take the first step today. Confidential, professional care — on your schedule, in your language.",
      ctaStart: "Start your assessment",
      ctaBrowse: "Browse providers",
      showingSpecialty: "Showing providers specialising in:",
      noProvidersFound: "No providers found",
      tryAdjust: "Try adjusting your filters.",
      searchCountry: "Search country...",
      providerFound: "provider found",
      providersFound: "providers found",
      pricesShownIn: "Prices shown in",
    },
    footer: {
      tagline: "Board-certified psychiatric care, wherever you are in the world. Compassionate, discreet, and on your schedule.",
      badges: ["Verified Providers", "HIPAA Secure", "24/7 Support"],
      platformTitle: "Platform",
      specialtiesTitle: "Specialties",
      supportTitle: "Support",
      platformLinks: [
        { label: "Find a Provider", href: "/providers" },
        { label: "Book a Session",  href: "/book" },
        { label: "My Appointments", href: "/appointments" },
        { label: "Specialties",     href: "/specialties" },
      ],
      specialties: ["Anxiety & Stress","Depression","PTSD & Trauma","ADHD","Bipolar Disorder","OCD"],
      supportLinks: ["Help Center","Privacy Policy","Terms of Service","Crisis Resources","Contact Us"],
      copyright: "2024 Clearhead Health Inc. All rights reserved.",
      notEmergency: "Not for emergency services. If you are in crisis, call 911 or 988.",
      crisisNote: "In crisis? Call or text 988 (Suicide & Crisis Lifeline) for immediate support 24/7.",
    },
    providerPage: {
      title: "Find a Provider",
      subtitle: "Board-certified specialists matched to your needs, priced in your local currency.",
      searchName: "Search by name...",
      allSpecialties: "All Specialties",
      anyGender: "Any gender",
      maleProviders: "Male providers",
      femaleProviders: "Female providers",
      availableNow: "Available now",
      showingSpecialty: "Showing providers specialising in:",
      noFound: "No providers found",
      tryAdjust: "Try adjusting your filters.",
      pricesIn: "Prices in:",
      searchCountry: "Search country...",
      available: "Available",
      waitlisted: "Waitlisted",
      insurance: "Insurance",
      exp: "y exp.",
      nextAvail: "Next:",
      specialtyOptions: [
        { value: "",                    label: "All Specialties" },
        { value: "Anxiety & Stress",    label: "Anxiety & Stress" },
        { value: "Depression",          label: "Depression" },
        { value: "PTSD & Trauma",       label: "PTSD & Trauma" },
        { value: "ADHD",                label: "ADHD" },
        { value: "Bipolar Disorder",    label: "Bipolar Disorder" },
        { value: "OCD",                 label: "OCD" },
        { value: "Grief & Loss",        label: "Grief & Loss" },
        { value: "Addiction & Recovery",label: "Addiction & Recovery" },
        { value: "Couples & Relationships",label: "Couples & Relationships" },
        { value: "Child & Adolescent",  label: "Child & Adolescent" },
        { value: "Psychiatry",          label: "Psychiatry" },
      ],
    },
  },
  ar: {
    dir: "rtl" as const,
    appName: "كليرهيد",
    tagline: "رعاية نفسية متخصصة، أينما كنت",
    subTagline: "تواصل مع أطباء نفسيين ومعالجين معتمدين يستمعون إليك حقاً. علاج مبني على الأدلة للقلق، الاكتئاب، اضطراب نقص الانتباه، اضطراب ما بعد الصدمة وأكثر — من راحة منزلك.",
    nav: {
      home: "الرئيسية", providers: "الأطباء", specialties: "التخصصات",
      mySessions: "جلساتي", platform: "المنصة", getStarted: "ابدأ الآن",
      pricing: "الأسعار", simulator: "محاكي الإيرادات", legal: "العقود والقانونية",
      addDoctor: "إضافة طبيب",
    },
    providers: {
      title: "ابحث عن مزود",
      subtitle: "متخصصون معتمدون يناسبون احتياجاتك، بأسعار بعملتك المحلية.",
      search: "البحث بالاسم...",
      allSpecialties: "جميع التخصصات",
      anyGender: "أي جنس",
      maleProviders: "أطباء ذكور",
      femaleProviders: "طبيبات",
      availableNow: "متاح الآن",
      found: "مزود تم العثور عليه",
      pricesIn: "الأسعار بـ",
      bookSession: "احجز جلسة",
      available: "متاح",
      waitlisted: "قائمة الانتظار",
      insurance: "تأمين",
      exp: "سنة خبرة",
      next: "القادم:",
      reviews: "تقييم",
    },
    intake: {
      stepOf: "خطوة",
      of: "من",
      yourJourney: "رحلتك تبدأ هنا",
      whatSupport: "ما نوع الدعم الذي تبحث عنه؟",
      chooseRight: "اختر ما يناسبك — يمكنك التعديل في أي وقت.",
      whatBrings: "ما الذي أحضرك هنا؟",
      chooseAll: "اختر كل ما ينطبق — سنخصص تطابقك.",
      anySymptoms: "هل تعرّف على أيٍّ من هذه؟",
      preselected: "اخترنا بناءً على ما شاركته. أزل أو أضف حسب الحاجة.",
      previousTherapy: "هل خضعت للعلاج النفسي من قبل؟",
      age: "كم عمرك؟",
      ageSubtitle: "يساعدنا في مطابقتك مع مزود ذو خبرة مع فئتك العمرية.",
      yearsOld: "سنة",
      gender: "كيف تعرّف عن نفسك؟",
      country: "أين تقيم؟",
      countrySubtitle: "سنطابق مزودين في منطقتك وسنعرض الأسعار بعملتك المحلية.",
      therapistGender: "هل لديك تفضيل لجنس المعالج؟",
      religious: "هل تعتبر نفسك متديناً أو روحياً؟",
      sessionFormat: "كيف تريد أن تلتقي؟",
      contactMethod: "كيف يجب أن نتواصل معك؟",
      whatsappNumber: "رقم واتساب",
      phoneNumber: "رقم الهاتف",
      emailAddress: "عنوان البريد الإلكتروني",
      howHeard: "شيء أخير — كيف عرفت عنا؟",
      termsTitle: "على وشك الانتهاء — راجع واقبل",
      termsSubtitle: "يرجى قراءة وقبول ما يلي قبل مطابقتك مع مزود.",
      iAgree: "قرأت وأقبل جميع الشروط",
      continueBtn: "متابعة",
      findTherapist: "ابحث عن معالجي",
      selectCountry: "اختر دولتك...",
      suggested: "مقترح",
      noPreference: "لا تفضيل",
      maleTherapis: "معالج ذكر",
      femaleTherapis: "معالجة أنثى",
      condition: "ما الذي تتعامل معه؟",
      conditionSubtitle: "اختر قلقك الرئيسي. يمكنك اختيار أكثر من واحد.",
      otherCondition: "صف قلقك",
      otherPlaceholder: "أخبرنا المزيد عما تمر به...",
      sessionDuration: "كم تريد أن تستغرق جلساتك؟",
      durationSubtitle: "الجلسات الأطول تعطي عمقاً أكبر. يمكنك التغيير في أي وقت.",
    },
    checkout: {
      title: "احجز جلستك",
      subtitle: "اختر موعداً وأكد حجزك.",
      provider: "المزود",
      specialty: "التخصص",
      duration: "مدة الجلسة",
      selectDate: "اختر تاريخاً",
      selectTime: "اختر موعداً",
      promoCode: "رمز ترويجي / إحالة",
      promoPlaceholder: "CLEAR20",
      apply: "تطبيق",
      orderSummary: "ملخص الطلب",
      session: "رسوم الجلسة",
      discount: "خصم",
      total: "المجموع",
      confirmBook: "تأكيد وحجز الجلسة",
      acceptTerms: "أقبل شروط الخدمة وسياسة الخصوصية",
      successTitle: "تم إرسال الحجز للموافقة",
      successSub: "حجزك قيد مراجعة المشرف. ستتلقى تأكيداً فور الموافقة عليه.",
      invalidCode: "رمز غير صالح",
      codeApplied: "تم التطبيق!",
      min: "دقيقة",
      paymentMethod: "طريقة الدفع",
      payCredit: "بطاقة ائتمانية / مدى",
      payZain: "زين كاش",
      payOrange: "أورنج موني",
      payClickPay: "كليك باي (الأردن)",
      cardNumber: "رقم البطاقة",
      cardExpiry: "تاريخ الانتهاء (MM/YY)",
      cardCvv: "CVV",
      cardName: "الاسم على البطاقة",
      walletNumber: "رقم هاتف المحفظة",
      pendingApproval: "في انتظار موافقة المشرف",
      patientId: "رقم المريض",
      callPlatform: "منصة الاتصال المرئي",
      doxyNote: "سيرسل مزودك رابط غرفة Doxy.me قبل جلستك. لا يلزم تنزيل أي برنامج.",
      noCancelNote: "الحجوزات غير قابلة للإلغاء بعد التأكيد. الرجاء اختيار موعدك بعناية.",
      backBtn: "رجوع",
    },
    addDoctor: {
      title: "انضم كمزود",
      subtitle: "تقدم لإدراج ممارستك على Clearhead. يراجع فريقنا جميع الطلبات خلال 48 ساعة.",
      fullName: "الاسم الكامل",
      title2: "اللقب المهني",
      specialty: "التخصص الرئيسي",
      bio: "السيرة المهنية",
      bioPlaceholder: "تدريبك وخبرتك ونهجك العلاجي...",
      languages: "اللغات المتحدث بها",
      nationality: "الجنسية / الدولة",
      price: "سعر الجلسة (دولار، 45 دقيقة)",
      experience: "سنوات الخبرة",
      credentials: "الشهادات / الاعتمادات",
      imageUrl: "رابط الصورة الشخصية",
      email: "البريد الإلكتروني للتواصل",
      phone: "رقم الهاتف",
      acceptsInsurance: "يقبل التأمين",
      submit: "تقديم الطلب",
      success: "تم تقديم الطلب! سنتواصل معك خلال 48 ساعة.",
    },
    terms: {
      notMedical: "Clearhead ليست خدمة طبية",
      notMedicalText: "الخدمات المقدمة عبر هذه المنصة ذات طابع إدراكي ونفسي وعلاجي. لا تشكل تشخيصاً طبياً أو علاجاً أو وصفاً من أي نوع. في حالات الطوارئ الطبية، اتصل بخدمات الطوارئ المحلية فوراً.",
      consent: "الموافقة المستنيرة",
      consentText: "بالمتابعة، تؤكد أنك تسعى طوعاً للحصول على دعم الصحة النفسية وتفهم أن الجلسات لأغراض علاجية ورفاهية فقط.",
      confidentiality: "السرية",
      confidentialityText: "جميع الجلسات خاصة وسرية. لا يجوز الإفصاح عن المعلومات إلا إذا كان هناك خطر وشيك على نفسك أو الآخرين، وفقاً للقانون المعمول به.",
      communication: "مراقبة الاتصالات",
      communicationText: "قد تُسجَّل الجلسات لضمان الجودة والإشراف السريري. سيتم إعلامك قبل أي تسجيل.",
      age: "متطلب السن",
      ageText: "تؤكد أن عمرك 18 عاماً أو أكثر، أو لديك موافقة والدية / وصي للوصول إلى هذه الخدمات.",
      jurisdiction: "الولاية القضائية",
      jurisdictionText: "تخضع هذه الشروط لقوانين الولاية القضائية التي يرخص فيها مزودك المختار للممارسة.",
    },
    journey: {
      phases: ["الفحص", "ملفك الشخصي", "التفضيلات", "الحجز"],
      careTypePhase: "المرحلة ١ · الفحص",
      careTypeTitle: "لمن هذا الفحص؟",
      careTypeSubtitle: "إجابتك تحدد نوع الفحص والمختص المناسب لك.",
      careTypeStart: "ابدأ الفحص",
      careTypes: [
        { id: "individual", label: "لنفسي",           sub: "علاج نفسي فردي للبالغين أو استشارة نفسية" },
        { id: "couples",    label: "لنا كزوجين",       sub: "إرشاد العلاقات والتواصل والثقة" },
        { id: "children",   label: "لطفلي أو مراهقي",  sub: "دعم متخصص لمن هم دون ١٨ عامًا" },
      ],
      k10IntroTitle: "فحص الضائقة النفسية",
      k10IntroText: "الأسئلة العشرة التالية مأخوذة من مقياس كيسلر للضائقة النفسية (K10) — أداة سريرية معتمدة عالميًا. فكّر في كيف شعرت خلال الـ ٤ أسابيع الماضية.",
      k10Privacy: "إجاباتك خاصة ولا يطلع عليها سوى مختصك المختار.",
      k10Badge: "K10 · الضائقة",
      k10Scale: [
        { val: 1, label: "لا شيء\nمن الوقت" },
        { val: 2, label: "القليل\nمن الوقت" },
        { val: 3, label: "بعض\nالوقت" },
        { val: 4, label: "معظم\nالوقت" },
        { val: 5, label: "كل\nالوقت" },
      ],
      k10Qs: [
        "كم مرة شعرت بالإرهاق دون سبب وجيه؟",
        "كم مرة شعرت بالتوتر أو الضغط النفسي؟",
        "كم مرة شعرت بتوتر شديد لا شيء يهدّئك؟",
        "كم مرة شعرت باليأس من المستقبل؟",
        "كم مرة شعرت بالقلق أو الانفعال؟",
        "كم مرة شعرت بقلق شديد لم تستطع الجلوس بهدوء؟",
        "كم مرة شعرت بالاكتئاب أو الحزن؟",
        "كم مرة شعرت أن كل شيء يتطلب جهدًا كبيرًا؟",
        "كم مرة شعرت بحزن شديد لا يخففه شيء؟",
        "كم مرة شعرت بانعدام القيمة؟",
      ],
      phq9IntroTitle: "فحص الاكتئاب",
      phq9IntroText: "الأسئلة التسعة التالية مأخوذة من استبيان صحة المريض (PHQ-9). فكّر في كم مرة واجهت كل حالة خلال الأسبوعين الماضيين.",
      phq9Disclaimer: "هذه أداة فحص فقط. تُشارك النتائج مع مختصك ولا تُستخدم للتشخيص.",
      phq9Badge: "PHQ-9 · الاكتئاب",
      phq9Header: "خلال الأسبوعين الماضيين، كم مرة أزعجتك...",
      phq9CrisisNote: "إذا كنت في أزمة، يرجى الاتصال بخط طوارئ الصحة النفسية أو خدمات الطوارئ المحلية فورًا.",
      phqScale: [
        { val: 0, label: "لا\nإطلاقًا" },
        { val: 1, label: "عدة\nأيام" },
        { val: 2, label: "أكثر من\nنصف الأيام" },
        { val: 3, label: "تقريباً\nكل يوم" },
      ],
      phq9Qs: [
        "ضعف الاهتمام أو المتعة في فعل الأشياء",
        "الشعور بالاكتئاب أو الإحباط أو اليأس",
        "صعوبة في النوم أو الاستيقاظ المتكرر أو النوم الزائد",
        "الشعور بالتعب أو نقص الطاقة",
        "ضعف الشهية أو الإفراط في الأكل",
        "الشعور بالسوء تجاه نفسك أو أنك فاشل أو خذلت نفسك أو عائلتك",
        "صعوبة في التركيز على الأشياء كالقراءة أو مشاهدة التلفاز",
        "التحرك أو الكلام ببطء شديد أو الشعور بالانفعال والتوتر الزائد",
        "أفكار بأنك ستكون أفضل حالًا لو كنت ميتًا أو أفكار بإيذاء نفسك",
      ],
      gad7IntroTitle: "فحص القلق",
      gad7IntroText: "اقتربنا من نهاية المرحلة الأولى. هذه الأسئلة السبعة من مقياس اضطراب القلق المعمم (GAD-7). فكّر في الأسبوعين الماضيين.",
      gad7Badge: "GAD-7 · القلق",
      gad7Qs: [
        "الشعور بالتوتر أو الانفعال أو الترقب",
        "عدم القدرة على إيقاف القلق أو التحكم فيه",
        "القلق الزائد حول أشياء مختلفة",
        "صعوبة في الاسترخاء",
        "القلق الشديد لدرجة صعوبة الجلوس بهدوء",
        "سرعة الانزعاج أو التهيج",
        "الشعور بالخوف كأن شيئًا سيئًا سيحدث",
      ],
      resultsPhase: "اكتمل الفحص",
      resultsTitle: "نتائجك",
      resultsSubtitle: "هذه نتائج فحص وليست تشخيصًا. سيراجعها مختص معتمد معك.",
      riskTitle: "أحد إجاباتك يستدعي الاهتمام",
      riskText: "أشرت إلى أفكار إيذاء الذات. سيراجع طبيب حالتك ويتواصل معك خلال ٢٤ ساعة. إذا كنت في خطر فوري، يرجى الاتصال بالطوارئ.",
      scoreLabels: ["الاكتئاب (PHQ-9)"],
      scoreLevels: ["خفيف جدًا", "خفيف", "معتدل", "شديد نسبيًا"],
      recommendedLabel: "الموصى به",
      screeningDisclaimer: "هذا ملخص فحص PHQ-9 للاكتئاب فقط — وليس تشخيصًا طبيًا.",
      recommendations: {
        couples:             { label: "معالج زوجي",                  reason: "متخصصون في ديناميكيات العلاقات والتواصل وحل النزاعات." },
        children:            { label: "متخصص الأطفال والمراهقين",    reason: "مدربون على التعامل مع العقول الأصغر في بيئة آمنة ومناسبة للعمر." },
        psychiatrist:        { label: "طبيب نفسي",                   reason: "نتائجك تشير إلى أعراض تستفيد أكثر من التقييم الطبي والرعاية النفسية الشاملة." },
        therapistDepression: { label: "معالج — متخصص الاكتئاب",      reason: "درجة PHQ-9 تشير إلى أن العلاج السلوكي المعرفي سيكون الأكثر فائدة." },
        counselor:           { label: "معالج / مستشار نفسي",          reason: "نتائجك تشير إلى ضغط خفيف. معالج داعم سيساعدك على بناء المرونة ومهارات التكيف." },
      },
      continueToProfile: "المتابعة إلى الملف الشخصي",
      profilePhase: "المرحلة ٢ · ملفك الشخصي",
      profileTitle: "أخبرنا عن نفسك",
      profileSubtitle: "هذا يساعد مختصك على فهم خلفيتك وتقديم رعاية أفضل.",
      firstNameLabel: "الاسم الأول",   firstNamePH: "محمد",
      lastNameLabel: "اسم العائلة",    lastNamePH: "الأحمد",
      dobLabel: "تاريخ الميلاد",
      genderLabel: "الجنس",
      nationalityLabel: "الجنسية / بلد الإقامة",
      maritalLabel: "الحالة الاجتماعية",
      occupationLabel: "المهنة", occupationPH: "مثال: معلم، مهندس، طالب...",
      educationLabel: "المستوى التعليمي",
      genderOpts: [
        { value: "male",       label: "ذكر" },
        { value: "female",     label: "أنثى" },
        { value: "nonbinary",  label: "غير ثنائي" },
        { value: "prefer_not", label: "أفضل عدم الإجابة" },
      ],
      maritalOpts: [
        { value: "single",    label: "أعزب / عزباء" },
        { value: "married",   label: "متزوج / ة" },
        { value: "partnered", label: "في علاقة" },
        { value: "divorced",  label: "مطلق / ة أو منفصل / ة" },
        { value: "widowed",   label: "أرمل / ة" },
      ],
      educationOpts: [
        { value: "high_school", label: "الثانوية العامة" },
        { value: "bachelors",   label: "بكالوريوس" },
        { value: "masters",     label: "ماجستير" },
        { value: "phd",         label: "دكتوراه" },
        { value: "vocational",  label: "مهني / تقني" },
        { value: "other",       label: "أخرى" },
      ],
      medTitle: "الخلفية الطبية والصحة النفسية",
      medSubtitle: "جميع المعلومات سرية ولا تُشارك إلا مع مختصك.",
      prevTherapyLabel: "هل سبق لك الخضوع للعلاج النفسي؟",
      prevDxLabel: "هل سبق تشخيصك بأي مما يلي؟ (اختر كل ما ينطبق)",
      familyDxLabel: "هل يوجد تاريخ عائلي لأمراض الصحة النفسية؟",
      medsLabel: "هل تتناول أي أدوية حاليًا؟",
      therapyOpts: [
        { value: "yes_helpful",     label: "نعم — كان مفيدًا" },
        { value: "yes_not_helpful", label: "نعم — لكنه لم يكن مفيدًا" },
        { value: "no",              label: "لا، هذه أول مرة لي" },
        { value: "unsure",          label: "غير متأكد / ة" },
      ],
      medicationOpts: [
        { value: "no",        label: "لا" },
        { value: "yes_psych", label: "نعم — أدوية نفسية" },
        { value: "yes_other", label: "نعم — أدوية أخرى" },
        { value: "unsure",    label: "غير متأكد / ة" },
      ],
      prevDxOptions: ["الاكتئاب","اضطراب القلق","الاضطراب ثنائي القطب","اضطراب نقص الانتباه (ADHD)","اضطراب ما بعد الصدمة (PTSD)","الوسواس القهري (OCD)","اضطراب الأكل","اضطراب الشخصية","الفصام","لا شيء مما سبق"],
      familyDxOptions: ["الاكتئاب","القلق","ثنائي القطب","الفصام","الإدمان","لا شيء في حدود علمي"],
      emergencyTitle: "جهة اتصال الطوارئ",
      emergencySubtitle: "شخص يمكننا التواصل معه في حالة طوارئ سريرية. هذا اختياري لكن موصى به.",
      emergencyNameLabel: "اسم جهة الاتصال",  emergencyNamePH: "الاسم الكامل",
      emergencyRelLabel: "صلة القرابة",        emergencyRelPH: "مثال: شريك الحياة، أحد الوالدين، صديق",
      emergencyPhoneLabel: "رقم الهاتف",       emergencyPhonePH: "+966 5X XXX XXXX",
      emergencyNote: "تُستخدم هذه المعلومات فقط في حالات الطوارئ السريرية الحقيقية.",
      prefsPhase: "المرحلة ٣ · التفضيلات",
      prefsTitle: "كيف تريد التواصل؟",
      prefsSubtitle: "حدد تفضيلات جلستك — يمكنك تغييرها لاحقًا.",
      formatLabel: "صيغة الجلسة",
      formatOpts: [
        { value: "video",     label: "مكالمة فيديو",  icon: "📹" },
        { value: "phone",     label: "مكالمة هاتفية", icon: "📞" },
        { value: "messaging", label: "مراسلة",         icon: "💬" },
      ],
      providerGenderLabel: "تفضيل جنس المختص",
      providerGenderOpts: [
        { value: "any",    label: "لا تفضيل" },
        { value: "male",   label: "مختص ذكر" },
        { value: "female", label: "مختصة أنثى" },
      ],
      timePrefLabel: "الوقت المفضل للجلسة",
      timeOpts: [
        { value: "any",       label: "مرن" },
        { value: "morning",   label: "الصباح (قبل الظهر)" },
        { value: "afternoon", label: "بعد الظهر" },
        { value: "evening",   label: "المساء (بعد الساعة ٥)" },
      ],
      contactLabel: "كيف يجب أن نتواصل معك؟",
      contactOpts: [
        { value: "email",    label: "البريد الإلكتروني", icon: "✉️" },
        { value: "whatsapp", label: "واتساب",             icon: "💬" },
      ],
      emailInputLabel: "عنوان البريد الإلكتروني", emailPH: "example@email.com",
      whatsappInputLabel: "رقم واتساب",             whatsappPH: "+966 5X XXX XXXX",
      findProvider: "ابحث عن مختصي",
      bookingPhase: "المرحلة ٤ · احجز جلستك",
      bookingTitle: "مختصوك المقترحون",
      bookingSubtitleBase: "بناءً على نتائج فحصك، نوصي بـ",
      bookingSubtitleCurrency: "الأسعار بـ",
      recommendedSection: "موصى به لك",
      otherSection: "مختصون آخرون",
      noProviders: "لم يتم العثور على مختصين. جرب مسح البحث.",
      searchPH: "ابحث بالاسم أو التخصص...",
      durationTitle: "مدة الجلسة",
      durationSubtitleBase: "الأسعار بـ",
      durationSubtitleNationality: "بناءً على جنسيتك.",
      minuteLabel: "دقيقة",
      bestValue: "أفضل قيمة",
      dateTitle: "اختر تاريخًا",
      dateSubtitle: "الجلسات متاحة خلال الـ ٦٠ يومًا القادمة.",
      timePickTitle: "اختر وقتًا",
      timePickSubtitleBase: "المواعيد المتاحة ليوم",
      timePickDateFirst: "اختر تاريخًا أولًا.",
      checkingSlots: "جارٍ التحقق من التوفر...",
      bookedSlotsNote: "موعد محجوز",
      bookedSlotsPluralNote: "مواعيد محجوزة",
      reviewTitle: "مراجعة وتأكيد",
      reviewSubtitle: "هل كل شيء صحيح؟ قم بتأكيد جلستك.",
      patientLabel: "المريض",
      reviewDateLabel: "التاريخ",
      reviewTimeLabel: "الوقت",
      reviewFormatLabel: "الصيغة",
      reviewCountryLabel: "الدولة",
      promoLabel: "رمز العرض",
      promoOptional: "اختياري",
      promoPH: "مثال: CLEAR20",
      applyBtn: "تطبيق",
      sessionFee: "رسوم الجلسة",
      discountLabel: "خصم",
      totalLabel: "المجموع",
      invalidPromo: "رمز غير صالح",
      termsText: "أقبل شروط الخدمة وسياسة الخصوصية. أفهم أن Clearhead منصة فحص وعلاج وليست خدمة طوارئ.",
      confirmBtn: "تأكيد وحجز الجلسة ←",
      securityNote: "متوافق مع HIPAA · مشفر تمامًا · إلغاء مجاني حتى ٢٤ ساعة",
      successTitle: "كل شيء جاهز!",
      successSub: "تم تأكيد جلستك مع",
      successDateLabel: "التاريخ",
      successTimeLabel: "الوقت",
      successDurationLabel: "المدة",
      successTotalLabel: "المجموع",
      shareBtn: "مشاركة عبر واتساب",
      copyBtn: "نسخ رابط الحجز",
      copiedBtn: "تم النسخ!",
      homeBtn: "العودة للرئيسية",
      backBtn: "رجوع",
      homeNavBtn: "الرئيسية",
      tapToAnswer: "اضغط على إجابة للمتابعة",
      continueBtn: "متابعة",
      continueToPrefs: "المتابعة إلى التفضيلات",
      reviewBookingBtn: "مراجعة الحجز",
      confirmBookBtn: "تأكيد وحجز الجلسة",
      browseProviders: "تصفح المختصين",
      selectedSuffix: "محدد",
      minLabel: "/ساعة",
      insuranceLabel: "تأمين",
      expLabel: "سنة خبرة",
    },
    landing: {
      heroAvailable: "مزودون متاحون الآن",
      heroChoose: "اختر نوع الرعاية التي تبحث عنها",
      heroServices: [
        { id: "individual", emoji: "🧠", title: "علاج فردي",              sub: "للبالغين ١٨ عامًا وما فوق" },
        { id: "couples",    emoji: "💑", title: "إرشاد زوجي",             sub: "لك أو مع شريكك" },
        { id: "children",  emoji: "🧒", title: "الأطفال والمراهقون",     sub: "دون ١٨ عامًا" },
      ],
      heroGetStarted: "ابدأ الآن",
      heroBrowse: "تصفح جميع المختصين",
      statsLabels: ["مختص", "مريض تم خدمته", "معدل الرضا", "دولة"],
      specialitiesTitle: "الحالات التي نعالجها",
      specialitiesSub: "رعاية متخصصة لكامل طيف احتياجات الصحة النفسية.",
      specialistsCount: "متخصص",
      viewAllSpecialties: "عرض جميع التخصصات",
      meetTitle: "تعرّف على مختصينا",
      meetSub: "جميع المزودين معتمدون ومدققو الخلفية قبل الانضمام إلى Clearhead.",
      browseAll: "تصفح الكل",
      viewProfile: "عرض الملف",
      howTitle: "كيف يعمل Clearhead",
      howSub: "البدء لا يستغرق أكثر من ٥ دقائق.",
      howSteps: [
        { num: "٠١", title: "أخبرنا بما تحتاجه",    desc: "أكمل استبياناً سريعاً لمساعدتنا على فهم أهدافك وتفضيلاتك." },
        { num: "٠٢", title: "ابحث عن مختص",          desc: "تصفح الأطباء النفسيين المعتمدين المتخصصين في مجال اهتمامك." },
        { num: "٠٣", title: "احجز جلستك",             desc: "اختر وقتاً يناسب جدولك — فيديو أو هاتف أو مراسلة." },
        { num: "٠٤", title: "ابدأ طريق التعافي",      desc: "احصل على رعاية مبنية على الأدلة من راحة منزلك، بشروطك." },
      ],
      getStartedToday: "ابدأ اليوم",
      trustItems: [
        { label: "متوافق مع HIPAA",  desc: "جميع الجلسات مشفرة تماماً وخاصة." },
        { label: "معتمدون فقط",       desc: "كل مزود معتمد بدقة ومدقق الخلفية." },
        { label: "٤٧ دولة نخدمها",   desc: "احصل على الرعاية في أي مكان بالعالم." },
        { label: "جدولة مرنة",        desc: "مواعيد مسائية وعطل نهاية الأسبوع متاحة." },
      ],
      testimonialsTitle: "ما يقوله مرضانا",
      testimonialsSub: "قصص حقيقية من أشخاص وجدوا طريقهم للأمام.",
      ctaTitle: "تستحق أن تشعر بتحسن.",
      ctaSub: "اتخذ الخطوة الأولى اليوم. رعاية سرية ومهنية — بجدولك، بلغتك.",
      ctaStart: "ابدأ تقييمك",
      ctaBrowse: "تصفح المختصين",
      showingSpecialty: "عرض المزودين المتخصصين في:",
      noProvidersFound: "لم يتم العثور على مزودين",
      tryAdjust: "جرب ضبط الفلاتر.",
      searchCountry: "ابحث عن دولة...",
      providerFound: "مزود",
      providersFound: "مزود",
      pricesShownIn: "الأسعار بـ",
    },
    footer: {
      tagline: "رعاية نفسية معتمدة من أطباء مرخصين، أينما كنت في العالم. رحيمة وسرية وبجدولك.",
      badges: ["مزودون موثقون", "آمن HIPAA", "دعم ٢٤/٧"],
      platformTitle: "المنصة",
      specialtiesTitle: "التخصصات",
      supportTitle: "الدعم",
      platformLinks: [
        { label: "ابحث عن مزود",   href: "/providers" },
        { label: "احجز جلسة",      href: "/book" },
        { label: "مواعيدي",         href: "/appointments" },
        { label: "التخصصات",        href: "/specialties" },
      ],
      specialties: ["القلق والضغط","الاكتئاب","اضطراب ما بعد الصدمة","اضطراب نقص الانتباه","ثنائي القطب","الوسواس القهري"],
      supportLinks: ["مركز المساعدة","سياسة الخصوصية","شروط الخدمة","موارد الأزمات","اتصل بنا"],
      copyright: "٢٠٢٤ Clearhead Health Inc. جميع الحقوق محفوظة.",
      notEmergency: "ليست لخدمات الطوارئ. إذا كنت في أزمة، اتصل بالطوارئ.",
      crisisNote: "في أزمة؟ اتصل بخط الدعم النفسي للحصول على المساعدة الفورية ٢٤/٧.",
    },
    providerPage: {
      title: "ابحث عن مزود",
      subtitle: "متخصصون معتمدون يناسبون احتياجاتك، بأسعار بعملتك المحلية.",
      searchName: "البحث بالاسم...",
      allSpecialties: "جميع التخصصات",
      anyGender: "أي جنس",
      maleProviders: "أطباء ذكور",
      femaleProviders: "طبيبات",
      availableNow: "متاح الآن",
      showingSpecialty: "عرض المزودين المتخصصين في:",
      noFound: "لم يتم العثور على مزودين",
      tryAdjust: "جرب ضبط الفلاتر.",
      pricesIn: "الأسعار بـ",
      searchCountry: "ابحث عن دولة...",
      available: "متاح",
      waitlisted: "قائمة الانتظار",
      insurance: "تأمين",
      exp: "سنة خبرة",
      nextAvail: "القادم:",
      specialtyOptions: [
        { value: "",                      label: "جميع التخصصات" },
        { value: "Anxiety & Stress",      label: "القلق والضغط" },
        { value: "Depression",            label: "الاكتئاب" },
        { value: "PTSD & Trauma",         label: "اضطراب ما بعد الصدمة" },
        { value: "ADHD",                  label: "اضطراب نقص الانتباه" },
        { value: "Bipolar Disorder",      label: "الاضطراب ثنائي القطب" },
        { value: "OCD",                   label: "الوسواس القهري" },
        { value: "Grief & Loss",          label: "الحزن والفقدان" },
        { value: "Addiction & Recovery",  label: "الإدمان والتعافي" },
        { value: "Couples & Relationships",label: "الأزواج والعلاقات" },
        { value: "Child & Adolescent",    label: "الأطفال والمراهقون" },
        { value: "Psychiatry",            label: "الطب النفسي" },
      ],
    },
  },
};

export type TranslationKeys = typeof translations.en;

type LangCtx = {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: TranslationKeys;
  dir: "ltr" | "rtl";
};

const LanguageContext = createContext<LangCtx>({
  lang: "en",
  setLang: () => {},
  t: translations.en,
  dir: "ltr",
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const saved = localStorage.getItem("clearhead_lang") as Lang | null;
    if (saved) return saved;
    const browserLang = navigator.language?.substring(0, 2);
    return browserLang === "ar" ? "ar" : "en";
  });

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("clearhead_lang", l);
  };

  useEffect(() => {
    document.documentElement.setAttribute("dir", translations[lang].dir);
    document.documentElement.setAttribute("lang", lang);
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t: translations[lang], dir: translations[lang].dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLang = () => useContext(LanguageContext);
