import { createContext, useContext, useState, useEffect, type ReactNode } from "react";

export type Lang = "en" | "ar";

export const translations = {
  en: {
    dir: "ltr" as const,
    appName: "Clearhead",
    tagline: "Expert psychiatric care, wherever you are",
    subTagline: "Connect with board-certified psychiatrists and therapists who truly listen. Evidence-based treatment for anxiety, depression, ADHD, PTSD, and more — from the comfort of home.",
    nav: {
      home: "Home", providers: "Providers", specialties: "Specialties",
      mySessions: "My Sessions", platform: "Platform", getStarted: "Get Started",
      pricing: "Pricing", simulator: "Revenue Simulator", legal: "Legal & Contracts",
      addDoctor: "Add a Doctor",
    },
    providers: {
      title: "Find a Provider",
      subtitle: "Board-certified specialists matched to your needs, priced in your local currency.",
      search: "Search by name...",
      allSpecialties: "All Specialties",
      anyGender: "Any gender",
      maleProviders: "Male providers",
      femaleProviders: "Female providers",
      availableNow: "Available now",
      found: "providers found",
      pricesIn: "Prices shown in",
      bookSession: "Book a Session",
      available: "Available",
      waitlisted: "Waitlisted",
      insurance: "Insurance",
      exp: "y exp.",
      next: "Next:",
      reviews: "reviews",
    },
    intake: {
      stepOf: "Step",
      of: "of",
      yourJourney: "Your journey starts here",
      whatSupport: "What kind of support are you looking for?",
      chooseRight: "Choose what feels right — you can always adjust later.",
      whatBrings: "What brings you here?",
      chooseAll: "Choose all that apply — we'll tailor your match.",
      anySymptoms: "Any of these feel familiar?",
      preselected: "We've pre-selected based on what you shared. Remove or add as needed.",
      previousTherapy: "Have you been in therapy before?",
      age: "How old are you?",
      ageSubtitle: "Helps us match you with a provider experienced with your age group.",
      yearsOld: "years old",
      gender: "How do you identify?",
      country: "Where are you based?",
      countrySubtitle: "We'll match providers in your region and show prices in your local currency.",
      therapistGender: "Any preference for your therapist's gender?",
      religious: "Do you consider yourself religious or spiritual?",
      sessionFormat: "How would you like to meet?",
      contactMethod: "How should we reach you?",
      whatsappNumber: "Your WhatsApp number",
      phoneNumber: "Your phone number",
      emailAddress: "Your email address",
      howHeard: "One last thing — how did you find us?",
      termsTitle: "Almost there — review and accept",
      termsSubtitle: "Please read and accept the following before we match you with a provider.",
      iAgree: "I have read and accept all terms",
      continueBtn: "Continue",
      findTherapist: "Find my therapist",
      selectCountry: "Select your country...",
      suggested: "suggested",
      noPreference: "No preference",
      maleTherapis: "Male therapist",
      femaleTherapis: "Female therapist",
      condition: "What are you dealing with?",
      conditionSubtitle: "Select your primary concern. You can pick more than one.",
      otherCondition: "Describe your concern",
      otherPlaceholder: "Tell us more about what you're going through...",
      sessionDuration: "How long would you like your sessions?",
      durationSubtitle: "Longer sessions give more depth. You can change this anytime.",
    },
    checkout: {
      title: "Book your Session",
      subtitle: "Choose a slot and confirm your appointment.",
      provider: "Provider",
      specialty: "Specialty",
      duration: "Session duration",
      selectDate: "Select a date",
      selectTime: "Select a time slot",
      promoCode: "Promo / referral code",
      promoPlaceholder: "CLEAR20",
      apply: "Apply",
      orderSummary: "Order summary",
      session: "Session fee",
      discount: "Discount",
      total: "Total",
      confirmBook: "Confirm & Book",
      acceptTerms: "I accept the Terms of Service and Privacy Policy",
      successTitle: "Appointment confirmed!",
      successSub: "You'll receive a confirmation via your chosen contact method.",
      invalidCode: "Invalid code",
      codeApplied: "applied!",
      min: "min",
    },
    addDoctor: {
      title: "Join as a Provider",
      subtitle: "Apply to list your practice on Clearhead. Our team reviews all applications within 48 hours.",
      fullName: "Full name",
      title2: "Professional title",
      specialty: "Primary specialty",
      bio: "Professional biography",
      bioPlaceholder: "Your training, experience, and therapeutic approach...",
      languages: "Languages spoken",
      nationality: "Nationality / Country",
      price: "Session price (USD, 45 min)",
      experience: "Years of experience",
      credentials: "Credentials / Certifications",
      imageUrl: "Profile photo URL",
      email: "Contact email",
      phone: "Phone number",
      acceptsInsurance: "Accepts insurance",
      submit: "Submit application",
      success: "Application submitted! We'll be in touch within 48 hours.",
    },
    terms: {
      notMedical: "Clearhead is NOT a medical service",
      notMedicalText: "The services provided through this platform are cognitive, psychological, and therapeutic in nature. They do not constitute medical diagnosis, treatment, or prescription of any kind. For medical emergencies, contact your local emergency services immediately.",
      consent: "Informed consent",
      consentText: "By proceeding, you confirm that you are voluntarily seeking mental health support and understand that sessions are for therapeutic and wellness purposes only.",
      confidentiality: "Confidentiality",
      confidentialityText: "All sessions are private and confidential. Information may only be disclosed if there is an imminent risk of harm to yourself or others, as required by applicable law.",
      communication: "Communication monitoring",
      communicationText: "Sessions may be recorded for quality assurance and clinical supervision purposes. You will be notified before any recording begins.",
      age: "Age requirement",
      ageText: "You confirm you are 18 years of age or older, or have parental / guardian consent to access these services.",
      jurisdiction: "Jurisdiction",
      jurisdictionText: "These terms are governed by the laws of the jurisdiction in which your selected provider is licensed to practice.",
    },
  },
  ar: {
    dir: "rtl" as const,
    appName: "كليرهيد",
    tagline: "رعاية نفسية متخصصة، أينما كنت",
    subTagline: "تواصل مع أطباء نفسيين ومعالجين معتمدين يستمعون إليك حقاً. علاج مبني على الأدلة للقلق، الاكتئاب، اضطراب نقص الانتباه، اضطراب ما بعد الصدمة وأكثر — من راحة منزلك.",
    nav: {
      home: "الرئيسية", providers: "الأطباء", specialties: "التخصصات",
      mySessions: "جلساتي", platform: "المنصة", getStarted: "ابدأ الآن",
      pricing: "الأسعار", simulator: "محاكي الإيرادات", legal: "العقود والقانونية",
      addDoctor: "إضافة طبيب",
    },
    providers: {
      title: "ابحث عن مزود",
      subtitle: "متخصصون معتمدون يناسبون احتياجاتك، بأسعار بعملتك المحلية.",
      search: "البحث بالاسم...",
      allSpecialties: "جميع التخصصات",
      anyGender: "أي جنس",
      maleProviders: "أطباء ذكور",
      femaleProviders: "طبيبات",
      availableNow: "متاح الآن",
      found: "مزود تم العثور عليه",
      pricesIn: "الأسعار بـ",
      bookSession: "احجز جلسة",
      available: "متاح",
      waitlisted: "قائمة الانتظار",
      insurance: "تأمين",
      exp: "سنة خبرة",
      next: "القادم:",
      reviews: "تقييم",
    },
    intake: {
      stepOf: "خطوة",
      of: "من",
      yourJourney: "رحلتك تبدأ هنا",
      whatSupport: "ما نوع الدعم الذي تبحث عنه؟",
      chooseRight: "اختر ما يناسبك — يمكنك التعديل في أي وقت.",
      whatBrings: "ما الذي أحضرك هنا؟",
      chooseAll: "اختر كل ما ينطبق — سنخصص تطابقك.",
      anySymptoms: "هل تعرّف على أيٍّ من هذه؟",
      preselected: "اخترنا بناءً على ما شاركته. أزل أو أضف حسب الحاجة.",
      previousTherapy: "هل خضعت للعلاج النفسي من قبل؟",
      age: "كم عمرك؟",
      ageSubtitle: "يساعدنا في مطابقتك مع مزود ذو خبرة مع فئتك العمرية.",
      yearsOld: "سنة",
      gender: "كيف تعرّف عن نفسك؟",
      country: "أين تقيم؟",
      countrySubtitle: "سنطابق مزودين في منطقتك وسنعرض الأسعار بعملتك المحلية.",
      therapistGender: "هل لديك تفضيل لجنس المعالج؟",
      religious: "هل تعتبر نفسك متديناً أو روحياً؟",
      sessionFormat: "كيف تريد أن تلتقي؟",
      contactMethod: "كيف يجب أن نتواصل معك؟",
      whatsappNumber: "رقم واتساب",
      phoneNumber: "رقم الهاتف",
      emailAddress: "عنوان البريد الإلكتروني",
      howHeard: "شيء أخير — كيف عرفت عنا؟",
      termsTitle: "على وشك الانتهاء — راجع واقبل",
      termsSubtitle: "يرجى قراءة وقبول ما يلي قبل مطابقتك مع مزود.",
      iAgree: "قرأت وأقبل جميع الشروط",
      continueBtn: "متابعة",
      findTherapist: "ابحث عن معالجي",
      selectCountry: "اختر دولتك...",
      suggested: "مقترح",
      noPreference: "لا تفضيل",
      maleTherapis: "معالج ذكر",
      femaleTherapis: "معالجة أنثى",
      condition: "ما الذي تتعامل معه؟",
      conditionSubtitle: "اختر قلقك الرئيسي. يمكنك اختيار أكثر من واحد.",
      otherCondition: "صف قلقك",
      otherPlaceholder: "أخبرنا المزيد عما تمر به...",
      sessionDuration: "كم تريد أن تستغرق جلساتك؟",
      durationSubtitle: "الجلسات الأطول تعطي عمقاً أكبر. يمكنك التغيير في أي وقت.",
    },
    checkout: {
      title: "احجز جلستك",
      subtitle: "اختر موعداً وأكد حجزك.",
      provider: "المزود",
      specialty: "التخصص",
      duration: "مدة الجلسة",
      selectDate: "اختر تاريخاً",
      selectTime: "اختر موعداً",
      promoCode: "رمز ترويجي / إحالة",
      promoPlaceholder: "CLEAR20",
      apply: "تطبيق",
      orderSummary: "ملخص الطلب",
      session: "رسوم الجلسة",
      discount: "خصم",
      total: "المجموع",
      confirmBook: "تأكيد وحجز",
      acceptTerms: "أقبل شروط الخدمة وسياسة الخصوصية",
      successTitle: "تم تأكيد الموعد!",
      successSub: "ستتلقى تأكيداً عبر طريقة الاتصال المختارة.",
      invalidCode: "رمز غير صالح",
      codeApplied: "تم التطبيق!",
      min: "دقيقة",
    },
    addDoctor: {
      title: "انضم كمزود",
      subtitle: "تقدم لإدراج ممارستك على Clearhead. يراجع فريقنا جميع الطلبات خلال 48 ساعة.",
      fullName: "الاسم الكامل",
      title2: "اللقب المهني",
      specialty: "التخصص الرئيسي",
      bio: "السيرة المهنية",
      bioPlaceholder: "تدريبك وخبرتك ونهجك العلاجي...",
      languages: "اللغات المتحدث بها",
      nationality: "الجنسية / الدولة",
      price: "سعر الجلسة (دولار، 45 دقيقة)",
      experience: "سنوات الخبرة",
      credentials: "الشهادات / الاعتمادات",
      imageUrl: "رابط الصورة الشخصية",
      email: "البريد الإلكتروني للتواصل",
      phone: "رقم الهاتف",
      acceptsInsurance: "يقبل التأمين",
      submit: "تقديم الطلب",
      success: "تم تقديم الطلب! سنتواصل معك خلال 48 ساعة.",
    },
    terms: {
      notMedical: "Clearhead ليست خدمة طبية",
      notMedicalText: "الخدمات المقدمة عبر هذه المنصة ذات طابع إدراكي ونفسي وعلاجي. لا تشكل تشخيصاً طبياً أو علاجاً أو وصفاً من أي نوع. في حالات الطوارئ الطبية، اتصل بخدمات الطوارئ المحلية فوراً.",
      consent: "الموافقة المستنيرة",
      consentText: "بالمتابعة، تؤكد أنك تسعى طوعاً للحصول على دعم الصحة النفسية وتفهم أن الجلسات لأغراض علاجية ورفاهية فقط.",
      confidentiality: "السرية",
      confidentialityText: "جميع الجلسات خاصة وسرية. لا يجوز الإفصاح عن المعلومات إلا إذا كان هناك خطر وشيك على نفسك أو الآخرين، وفقاً للقانون المعمول به.",
      communication: "مراقبة الاتصالات",
      communicationText: "قد تُسجَّل الجلسات لضمان الجودة والإشراف السريري. سيتم إعلامك قبل أي تسجيل.",
      age: "متطلب السن",
      ageText: "تؤكد أن عمرك 18 عاماً أو أكثر، أو لديك موافقة والدية / وصي للوصول إلى هذه الخدمات.",
      jurisdiction: "الولاية القضائية",
      jurisdictionText: "تخضع هذه الشروط لقوانين الولاية القضائية التي يرخص فيها مزودك المختار للممارسة.",
    },
  },
};

export type TranslationKeys = typeof translations.en;

type LangCtx = {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: TranslationKeys;
  dir: "ltr" | "rtl";
};

const LanguageContext = createContext<LangCtx>({
  lang: "en",
  setLang: () => {},
  t: translations.en,
  dir: "ltr",
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const saved = localStorage.getItem("clearhead_lang") as Lang | null;
    if (saved) return saved;
    const browserLang = navigator.language?.substring(0, 2);
    return browserLang === "ar" ? "ar" : "en";
  });

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("clearhead_lang", l);
  };

  useEffect(() => {
    document.documentElement.setAttribute("dir", translations[lang].dir);
    document.documentElement.setAttribute("lang", lang);
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t: translations[lang], dir: translations[lang].dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLang = () => useContext(LanguageContext);
